export const specialDealItems = [
  {
    imageSrc: "/images/specialdeal.jpeg",
    altText: "Butter Chicken",
    rating: 4.8,
    badgeText: "Chef's Special",
    title: "Butter Chicken",
    price: 12.99,
    oldPrice: 15.99,
    calories: 450,
  },
  {
    imageSrc: "/images/specialdeal.jpeg",
    altText: "Paneer Tikka",
    rating: 4.6,
    badgeText: "Vegetarian",
    title: "Paneer Tikka",
    price: 9.99,
    oldPrice: 11.49,
    calories: 380,
  },
  {
    imageSrc: "/images/specialdeal.jpeg",
    altText: "Hyderabadi Biryani",
    rating: 4.9,
    title: "Hyderabadi Biryani",
    price: 14.5,
    calories: 520,
  },
  {
    imageSrc: "/images/specialdeal.jpeg",
    altText: "Gulab Jamun",
    rating: 4.7,
    badgeText: "Dessert",
    title: "Gulab Jamun",
    price: 4.25,
    oldPrice: 5.0,
  },
];
